### ISSUE TITLE
今天被封号了。

### ISSUE THREAD

**Issue by abing7k** [SFHJavaer/R3nzSkinTencent#34]
今天被封号了，封了一个月，r3nz用了一年了，第一次被封

**Comment by NavoNivalis** [comment]
+1

**Comment by Yoshinooo520** [comment]
+1 封一周

**Comment by 2jduead** [comment]
+1

**Comment by az7139** [comment]
+1

**Comment by windyz1** [comment]
嗯，前天我也被封掉了

**Comment by vinland100** [comment]
+1

**Comment by pumpkin12135** [comment]
我倒是没被封，我一直闪退

**Comment by EternallyH40** [comment]
你们确定用的是14.17.001版本？我的暂时没出现问题

**Comment by EternallyH40** [comment]
你们确定用的是14.17.001版本？在训练模式暂时没出现问题

**Comment by xslzlccc** [comment]
> 今天被封号了，封了一个月，r3nz用了一年了，第一次被封

+1

**Comment by xslzlccc** [comment]
+1

**Comment by xslzlccc** [comment]
> 你们确定用的是14.17.001版本？在训练模式暂时没出现问题

对比了hash，确定是这个版本。我的也是一个月，去微信申请才解封的。我有个朋友就没被封，情况不同。

**Comment by MoLu10086** [comment]
刚打完一把，被封7天，使用第三方插件

**Comment by DMQIUIZIHXGJ** [comment]
今天被封了一个月。用了感觉快两年了？第一次被封。

**Comment by MoLu10086** [comment]
由于 Riot Games 将[Valorant 的 Vanguard 反作弊功能引入英雄联盟](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/24169857932435-Riot-Vanguard-FAQ-League-of-Legends)R3nzSkin不再受支持。这是原本R3NZ的原作者原文，现在封号的几率还是很大的。谨慎使用吧

**Comment by GOVG-LHS** [comment]
ok thanks for everthing you did🥰在 "MoLu." ***@***.***>，2024年10月30日 21:43写道：
由于 Riot Games 将Valorant 的 Vanguard 反作弊功能引入英雄联盟R3nzSkin不再受支持。这是原本R3NZ的原作者原文，现在封号的几率还是很大的。谨慎使用吧

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/SFHJavaer/R3nzSkinTencent/issues/34#issuecomment-2447205295",
"url": "https://github.com/SFHJavaer/R3nzSkinTencent/issues/34#issuecomment-2447205295",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SFHJavaer** [comment]
使用的人多了，原来的R3代码已经被定向检测了，暂时不知道怎么改进来防封，其他作者应该有另加防封的，能力所限，本仓库暂时存档，感谢理解。
